---
# Project Information
site_name: chaos2csv
site_author: MaKaNu
site_description: This tool tries to assemble different plain text structures, which makes kind of sense for humans but not for computers. The plain text file might be a result of different print statements passed into a file or anything else which may have caused this chaos.

# Repository information
repo_name: makanu/chaos2csv
repo_url: https://github.com/makanu/chaos2csv
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 MaKaNu

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/makanu
      name: makanu on GitHub

# Page tree
nav:
  - Home: index.md
